spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://localhost/accountsdb
    username: root
    password: root
  jpa:
    show-sql: true
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka