training: spring-boot
welcome: Welcome to ${training}

person:
  datasource:
    jdbc-url: jdbc:mysql://localhost/training
    username: root
    password: root


account:
  datasource:
    jdbc-url: jdbc:mysql://localhost/accountsdb
    username: root
    password: root
spring:
  jpa:
    properties:
      hibernate.enable_lazy_load_no_trans: true
    show-sql: true
