spring:
  application:
    name: bank-ui
  mvc:
    view:
      prefix: /
      suffix: .jsp
server:
  port: 8080


account:
  service:
    base:
      #url: http://localhost:7000/api/v1
      url: http://localhost:8081/account

#actuator configuration settings
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    beans:
      enabled: true
    shutdown:
      enabled: true
eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://localhost:8761/eureka
